[package]
name = "erk-dom"
description = "Erk Engine DOM: document tree management."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
html5ever = "=0.39.0"

[lints]
workspace = true
